config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'static_pages#home'
  
  get '/search', to: 'static_pages#search'

  root 'static_pages#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  post   '/users/import', to: 'users#import'
  
  resources :topics, except: [:edit, :update]
  
  resources :questions do
    resources :answers, only: [:create, :update, :destroy, :edit] do
      member do
        post 'upvote' => 'ratings#upvote'
        post 'downvote' => 'ratings#downvote'
      end
    end
  end
  
  resources :courses, except: :index
  

  

end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    belongs_to :topic

    has_many :answers, dependent: :destroy
    
    default_scope -> { order(created_at: :desc) }
    
    validates :title, presence: true, length: {maximum: 140}
    validates :content, presence: true
    validates :user, presence: true
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    authorize Question
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answers = @question.answers.all
  end

  # GET /questions/new
  def new
    @question = Question.new
    authorize @question
    @topics = Topic.all
  end

  # GET /questions/1/edit
  def edit
    authorize @question
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    authorize @question
    @question.user = current_user
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        @topics = Topic.all
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    authorize @question
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    authorize @question
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :topic_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <div class="mdl-card__supporting-text">
    <%= render 'shared/error_messages', object: f.object %>
    
    <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label topic-select">
      <%= f.collection_select( :topic_id, Topic.all, :id, :title, {include_blank: true}, {:class => 'required mdl-selectfield__select'}) %>
      <label class="mdl-selectfield__label">Topic</label>
      <span class="mdl-selectfield__error">Input is not a topic!</span>
    </div>    
    
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fullwidth">
        <%= f.label :title, :class => 'mdl-textfield__label'%>
        <%= f.text_field :title, :class => 'mdl-textfield__input'%>
    </div>
  
    <div class="mdl-textfield mdl-js-textfield fullwidth">
      <%= f.label :content, :class => 'mdl-textfield__label' %>
      <%= f.text_area :content, :class => 'mdl-textfield__input', placeholder: "Compose a question...", rows: "15" %>
    </div>
  </div>
  
  <div class="mdl-card__actions mdl-card--border">
    <%= f.submit :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'%>
    <%= link_to 'Cancel', home_path, :class => 'mdl-button mdl-js-button mdl-js-ripple-effect'%>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="section__circle-container mdl-cell mdl-cell--1-col mdl-cell--2-col-phone center-this">
  <!-- answer count goes here -->
  <i class="material-icons mdl-badge mdl-badge--overlap mdl-list__item-icon question-badge" data-badge="<%= question.answers.count %>">question_answer</i>
  <% if logged_in? and current_user.permission? :post_manage %>
    <div class = "admin-buttons">
      <%= link_to edit_question_path(question) ,:method => :get do %>
        <i class="material-icons question-button">edit</i>
      <% end %>
      <%= link_to question, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="material-icons question-button">delete</i>
      <% end %>
    </div>
  <% end %>
</div>
<div class="section__text answer__text mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--4-col-phone">
  <div class="question-title"><a href="<%= question_path question %>"><%= question.title %></a></div>
  <small>Posted <%= time_ago_in_words(question.created_at) %> ago by <b><%= link_to question.user.name, question.user %></b></small>
  </br>
  <% if question.answers.any? %>
    <small>Last answer given <%= time_ago_in_words question.answers.last.created_at %> ago.</small>
  <% else %>
    <small>No answers yet.</small>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <div class="mdl-cell mdl-cell--8-col mdl-shadow--4dp mdl-card">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Edit Question</h2>
        </div>
            <%= render 'form', question: @question %>
    </div>
</div>
<!--<%= link_to 'View', @question, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent page-loose-button' %>-->

app/views/questions/index.html.erb
<% if notice %>
<section class="mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section notice-upvote">
  <div class="mdl-card">
    <div class="mdl-card__supporting-text">
        <%= notice %>
        <i class="material-icons float-right dismiss">clear</i>
    </div>
  </div>
</section>
<% end %>

<div class="our-mdl">
  <div class="qa-panel">
    <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section mdl-cell--10-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
      <!--<div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>-->
      <div class="mdl-card mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
        <div class="mdl-card__title">
          <h2 class="mdl-card__title-text">All Questions</h2>
        </div>
        <div class="mdl-card__supporting-text">
          <div class=" mdl-grid mdl-grid--no-spacing answer-grid">
            <%= render @questions %>
          </div>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to 'Create New Question', new_question_path, :class => 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
        </div>
      </div>
    </section>
  </div>
</div>
<br>

app/views/questions/new.html.erb
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>
    <div class="mdl-cell mdl-cell--8-col mdl-shadow--4dp mdl-card">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Create New Question</h2>
        </div>
        
        <%= render 'form', question: @question %>
    
    </div>
</div>
<!-- <script>
//     document.addEventListener('turbolinks:load', function() {
//         componentHandler.upgradeDom();
//     });
// </script> -->

app/views/questions/show.html.erb
<div class="our-mdl">
  
  <!-- Begin Question Section -->
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section mdl-cell--10-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
    <div class="mdl-card mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
      <div class="mdl-card__supporting-text">
          <h4><%= @question.title %></h4>
          <div class="markdown-body"><%= parse_markdown @question.content %></div>
      </div>
      <% if logged_in? and current_user.permission? :post_manage %>
        <div class="mdl-card__actions mdl-card--border">
            <%= link_to 'Edit', edit_question_path(@question), :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect' %>
            <%= link_to 'Delete', @question, :class => 'mdl-button mdl-js-button mdl-js-ripple-effect', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    </div>
  </section>
  
  <!-- Begin Answers Section -->
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section mdl-cell--10-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
    <div class="mdl-card mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone answer-section">
      <div class="mdl-card__supporting-text">
        <% if @question.answers.any? %>
          <h4>Answers (<%= @question.answers.count %>)</h4>
          <div class=" mdl-grid mdl-grid--no-spacing answer-grid">
            <%= render @answers %>
          </div>
        <% else %>
          <h4>No Answers. Be the first to help!</h4>
        <% end %>
      </div>
      <% if logged_in? and current_user.permission? :post %>
        <div class="mdl-card__actions mdl-card--border">
          <span class = "mdl-button new-answer-button">Create New Answer</span>
          <%= render 'answers/form' %>
        </div>
      <% end %>
    </div>
  </section>
  
</div>

<script>
  
  $( ".dismiss" ).click(function() {
    $(".dismiss").parent().parent().addClass("hidden");
  });
  
  $( ".new-answer-button" ).click(function() {
    
    $('.new-answer-button').hide();
    $('.answer-form').show(250);
    
    // $(".new-answer-button").addClass("hidden");
    // $(".answer-form").addClass("visible").removeClass("hidden")
  });
</script>