config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'static_pages#home'
  
  get '/search', to: 'static_pages#search'

  root 'static_pages#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  post   '/users/import', to: 'users#import'
  
  resources :topics, except: [:edit, :update]
  
  resources :questions do
    resources :answers, only: [:create, :update, :destroy, :edit] do
      member do
        post 'upvote' => 'ratings#upvote'
        post 'downvote' => 'ratings#downvote'
      end
    end
  end
  
  resources :courses, except: :index
  

  

end

app/models/topic.rb
class Topic < ApplicationRecord
  acts_as_paranoid
  
  has_many :questions
  
  validates :title, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :destroy]
  
  def show
    @questions = @topic.questions
  end
  
  def new
    authorize Topic
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      flash[:success] = "Topic created."
      redirect_to @topic
    else
      flash.now[:danger] = "Topic not created."
      render :new
    end
  end

  def destroy
    authorize @topic
    @topic.destroy
  end
  
  def index
    @topics = Topic.all
  end
  
  private 
  
    def set_topic
      @topic = Topic.find(params[:id])
    end
  
    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="mdl-card__supporting-text">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fullwidth">
      <div>
        <%= f.label :title, :class => 'mdl-textfield__label' %>
        <%= f.text_field :title, class: 'form-control mdl-textfield__input' %>
      </div>
    </div>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <%= f.submit "Create Topic", :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent'%>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class="section__circle-container mdl-cell mdl-cell--1-col mdl-cell--2-col-phone center-this">
  <!-- answer count goes here -->
  <i class="material-icons mdl-badge mdl-badge--overlap mdl-list__item-icon question-badge" data-badge="<%= topic.questions.count %>">folder</i>
  <% if logged_in? and current_user.permission? :topic_manage %>
    <div class = "admin-buttons">
      <%= link_to topic, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="material-icons question-button">delete</i>
      <% end %>
    </div>
  <% end %>
</div>
<div class="section__text answer__text mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--4-col-phone">
  <div class="question-title"><a href="<%= topic_path topic %>"><%= topic.title %></a></div>
  <small>Created <%= time_ago_in_words(topic.created_at) %> ago</small>
  </br>
  <% if topic.questions.any? %>
    <small>Last question asked <%= time_ago_in_words topic.questions.last.created_at %> ago.</small>
  <% else %>
    <small>No questions asked yet.</small>
  <% end %>
</div>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/index.html.erb
<div class="our-mdl">
  <div class="qa-panel">
    <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section mdl-cell--10-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
      <!--<div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>-->
      <div class="mdl-card mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
        <div class="mdl-card__title">
          <h2 class="mdl-card__title-text">Topics</h2>
        </div>
        <div class="mdl-card__supporting-text">
          <div class=" mdl-grid mdl-grid--no-spacing answer-grid">
            <%= render @topics %>
          </div>
        </div>
        <% if logged_in? and current_user.permission? :topic %>
          <div class="mdl-card__actions mdl-card--border">
            <%= link_to 'Create New Topic', new_topic_path, :class => 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
          </div>
        <% end %> 
      </div>
    </section>
  </div>
</div>
<br>

app/views/topics/new.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section mdl-cell--4-col mdl-cell--6-col-tablet login-form">
  <div class="mdl-cell mdl-cell--12-col mdl-shadow--4dp mdl-card">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">New Topic</h2>
    </div>
    <%= render 'form', topic: @topic %>
  </div>
</section>

app/views/topics/show.html.erb
<div class="our-mdl">
  <div class="qa-panel">
    <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section mdl-cell--10-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
      <!--<div class="mdl-cell mdl-cell--2-col mdl-cell--hide-tablet mdl-cell--hide-phone"></div>-->
      <div class="mdl-card mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
        <div class="mdl-card__title">
          <h2 class="mdl-card__title-text"><%= @topic.title %></h2>
        </div>
        <div class="mdl-card__supporting-text">
          <div class=" mdl-grid mdl-grid--no-spacing answer-grid">
            <%= render @questions %>
          </div>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to 'Create New Question', new_question_path, :class => 'mdl-button mdl-js-button mdl-js-ripple-effect' %>
        </div>
      </div>
    </section>
  </div>
</div>
<br>