config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'static_pages#home'
  
  get '/search', to: 'static_pages#search'

  root 'static_pages#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  post   '/users/import', to: 'users#import'
  
  resources :topics, except: [:edit, :update]
  
  resources :questions do
    resources :answers, only: [:create, :update, :destroy, :edit] do
      member do
        post 'upvote' => 'ratings#upvote'
        post 'downvote' => 'ratings#downvote'
      end
    end
  end
  
  resources :courses, except: :index
  

  

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  has_many :ratings, dependent: :destroy
  
  validates :content, presence: true
  validates :user, presence: true
  default_scope -> { order(created_at: :asc) }
  
  def upvote_count
    ratings.upvotes.count
  end
  
  def downvote_count
    ratings.downvotes.count
  end
  
  def overall_rating
    upvote_count - downvote_count
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :set_answer, only: [:update, :destroy, :edit]
    
    def create
        authorize Answer
        
        @question = Question.find(params[:question_id])
        @answer = @question.answers.build(answer_params)
        @answer.user = current_user
        
        if @answer.save
            flash[:success] = 'Answer was added.'
            redirect_to @question
        else
            flash[:danger] = 'Answer could not be added.'
            redirect_to @question
        end
    end
    
    def update
        authorize @answer
        
        if @answer.update(answer_params)
            flash[:success] = "Answer was updated."
            redirect_to @answer.question
        else
            flash[:danger] = "Answer could not be updated."
            redirect_to @answer.question
        end
    end
    
    def destroy
        authorize @answer
        
        @question = @answer.question
        @answer.destroy
        flash[:success] = "Answer was destroyed."
        redirect_to @question
    end
    
    def edit
        
    end
    
    private
    
        # Use callbacks to share common setup or constraints between actions.
        def set_answer
            @answer = Answer.find(params[:id])
        end
    
        def answer_params
            params.require(:answer).permit(:content)
        end
    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="section__circle-container mdl-cell mdl-cell--1-col mdl-cell--2-col-phone center-this">
  <% if positive_rating answer.overall_rating %>
    <div class="its-a-circle im-green"><%= answer.overall_rating %></div>
  <% else %>
    <div class="its-a-circle im-red"><%= answer.overall_rating %></div>
  <% end %>
  <div class = "thumbs">
    <%= link_to upvote_question_answer_path(question_id: answer.question.id, id: answer.id), :class => "thumb-up",:method => :post do %>
      <i class="material-icons thumb">thumb_up</i>
    <% end %>
    <%= link_to downvote_question_answer_path(question_id: answer.question.id, id: answer.id), :class => "thumb-down",:method => :post do %>
        <i class="material-icons thumb">thumb_down</i>
    <% end %>
  </div>
</div>
<div class="section__text answer__text mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--4-col-phone answer-divs">
    <small>Posted <%= time_ago_in_words(answer.created_at) %> ago by <%= link_to answer.user.name, answer.user %>.</small>
    <div class="markdown-body"><%= parse_markdown answer.content %></div>
    <% if logged_in? and current_user.permission? :post_manage %>
      <button id="answer-menu-<%= answer.id %>" class="mdl-button mdl-js-button mdl-button--icon answer_dropdown">
        <i class="material-icons">more_vert</i>
      </button>
      <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="answer-menu-<%= answer.id %>">
        <%= link_to question_answer_path(answer.question, answer), method: :delete, data: { confirm: 'Are you sure?' } do%>
          <li class="mdl-menu__item">Delete</li>
        <% end %>
        <%= link_to edit_question_answer_path(answer.question, answer), data: {} do%>
          <li class="mdl-menu__item">Edit</li>
        <% end %>
      </ul>
    <% end %>
</div>

app/views/answers/_edit_form.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp question-section mdl-cell--10-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
    <div class="mdl-card mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
        <div class="mdl-card__title">
          <h2 class="mdl-card__title-text">Edit Question</h2>
        </div>
        <%= form_for(answer, url: question_answer_path) do |f| %>
            <div class="mdl-card__supporting-text">
                <div class=" mdl-grid mdl-grid--no-spacing answer-grid">
                    <div class="mdl-textfield mdl-js-textfield answer-textfield">
                        <label class="mdl-textfield__label" for="answer_content">Compose a new answer...</label>
                        <%= f.text_area :content,  :class => 'mdl-textfield__input', placeholder: "Compose a new answer...", rows: "5" %>
                    </div>
                </div>
            </div>
            <div class="mdl-card__actions mdl-card--border">
                  <%= f.submit :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent page-loose-button' %>
            </div>
        <% end %>
    </div>
</section>

app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <%= hidden_field_tag :question_id, @question.id %>
  <div class="answer-form"> <!-- hidden -->
    <div class="mdl-textfield mdl-js-textfield answer-textfield">
      <label class="mdl-textfield__label" for="answer_content">Compose a new answer...</label>
      <%= f.text_area :content,  :class => 'mdl-textfield__input', placeholder: "Compose a new answer...", rows: "5" %>
    </div>
    <div class="actions">
      <%= f.submit :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent page-loose-button' %>
    </div>
  </div>
<% end %>

app/views/answers/edit.html.erb
<%= render 'edit_form', answer: @answer %>