config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'static_pages#home'
  
  get '/search', to: 'static_pages#search'

  root 'static_pages#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  post   '/users/import', to: 'users#import'
  
  resources :topics, except: [:edit, :update]
  
  resources :questions do
    resources :answers, only: [:create, :update, :destroy, :edit] do
      member do
        post 'upvote' => 'ratings#upvote'
        post 'downvote' => 'ratings#downvote'
      end
    end
  end
  
  resources :courses, except: :index
  

  

end

app/views/layouts/_footer.html.erb
<footer class="mdl-mini-footer our-footer">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">NKUNet</div>
    <ul class="mdl-mini-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul>
  </div>
  <div class="mdl-mini-footer__right-section">
    <ul class="mdl-mini-footer__link-list">
      <li class="mini-footer-social-btn">
        <a href="https://github.com/CSC-440-Sp2017-NKU/team-project-high-speed-rail" class="social-btn github-img" role="button" title="GitHub"></a>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><a href="<%= root_path %>">NKUNet</a></span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <% if logged_in? and current_user.permission? :post %>
          <a class="mdl-navigation__link" href="<%= new_question_path %>">New Question</a>
        <% end %>
      </nav>
      
      <%= form_tag search_path, method: :get do %>
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
          <label class="mdl-button mdl-js-button mdl-button--icon" for="search_field">
            <i class="material-icons">search</i>
          </label>
          <div class="mdl-textfield__expandable-holder">
            <input class="mdl-textfield__input" type="text" id="search_field" name="search">
          </div>
        </div>
      <% end %>
    </div>
  </header>
  <div class="mdl-layout__drawer drawer">
    <span class="mdl-layout-title">
      <% if logged_in? %>
        <span class="username-display"><%= current_user.name %></span>
      <% else %>       
        <span class="drawer-title">NKUNet</span>
      <% end %>
    </span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="<%= root_path %>"><i class="material-icons">home</i> Home</a>
      <% if logged_in? and current_user.permission? :post %>
        <a class="mdl-navigation__link" href="<%= new_question_path %>"><i class="material-icons">question_answer</i> New Question</a>
      <% end %>
      <a class="mdl-navigation__link" href="<%= topics_path %>"><i class="material-icons">folder</i> Topics</a>
      
      <% if logged_in? %>
        <%= link_to current_user, class: "mdl-navigation__link" do %>
          <i class="material-icons">account_circle</i> Profile
        <% end %>
      <% end %> 
      
      <% if logged_in? and current_user.permission? :topic %>
        <a class="mdl-navigation__link" href="<%= new_topic_path %>"><i class="material-icons">create_new_folder</i> Create New Topic</a>
      <% end %> 
      
      <% if logged_in? and current_user.permission? :user_manage %>
        <a class="mdl-navigation__link" href="<%= new_user_path %>"><i class="material-icons">person_add</i> Create New User</a>
      <% end %> 
      
      <% if logged_in? and current_user.permission? :course_manage %>
        <a class="mdl-navigation__link" href="<%= new_course_path %>"><i class="material-icons">group_add</i> Create New Course</a>
      <% end %> 
      
      <div class="drawer-separator"></div>
      <% if logged_in? %>
        <%= link_to logout_path, :method => :delete, :class => "mdl-navigation__link" do %>
          <i class="material-icons flipped">exit_to_app</i> Sign Out
        <% end %>
      <% else %>
        <%= link_to login_path, :class => "mdl-navigation__link" do %>
          <i class="material-icons">exit_to_app</i> Sign In
        <% end %>
      <% end %>
    </nav>
  </div>

app/views/layouts/_rails_defaults.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'https://cdn.rawgit.com/CreativeIT/getmdl-select/master/getmdl-select.min.css', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'https://cdn.rawgit.com/CreativeIT/getmdl-select/master/getmdl-select.min.js', 'data-turbolinks-track' => true %>
<meta name="turbolinks-cache-control" content="no-cache">
<%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title yield(:title) %></title>
  <%= render 'layouts/rails_defaults' %>
</head>
<body>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  
  <%= render 'layouts/header' %>
  
  <main class="mdl-layout__content">
    
    <div class="page-content">
      <% flash.each do |message_type, message| %>
        <div class="notice-text" style="display:none;"><%= message %></div>
        <div class="mdl-js-snackbar mdl-snackbar">
          <div class="mdl-snackbar__text <%= message_type %>"></div>
          <button class="mdl-snackbar__action" type="button"></button>
        </div>
      <% end %>
      
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
    
    <%= render 'layouts/footer' %>
    
  </main>
</div>

</body>
</html>